declare module "*.jpg";
declare module "*.svg";
declare module "*.png";
declare module "*.mov";
declare module "*.ttf";
declare module "*.txt";
declare module "*.otf";
declare module "*.mp4";
declare module "*.ogg";
